// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBBQzwtdDFxposYxxFmlEzbNt3ec52zc',
    appId: '1:29464535100:web:92d404635957afcb40e339',
    messagingSenderId: '29464535100',
    projectId: 'iot-feeder-f8e4f',
    authDomain: 'iot-feeder-f8e4f.firebaseapp.com',
    databaseURL: 'https://iot-feeder-f8e4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-feeder-f8e4f.appspot.com',
    measurementId: 'G-21KM6Z0HBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCryKVu7MiUTRKuSkrLWuXjdXA1Vzs2-dA',
    appId: '1:29464535100:android:5e872110b8acce1c40e339',
    messagingSenderId: '29464535100',
    projectId: 'iot-feeder-f8e4f',
    databaseURL: 'https://iot-feeder-f8e4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-feeder-f8e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrmEpqrbW0hq7W_QA5flSrjcpze7XSnQ',
    appId: '1:29464535100:ios:d637abd4a615e25340e339',
    messagingSenderId: '29464535100',
    projectId: 'iot-feeder-f8e4f',
    databaseURL: 'https://iot-feeder-f8e4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-feeder-f8e4f.appspot.com',
    iosClientId: '29464535100-4uka1bruqffkdihp9uqsmruur3q3nf1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFeeder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrmEpqrbW0hq7W_QA5flSrjcpze7XSnQ',
    appId: '1:29464535100:ios:d637abd4a615e25340e339',
    messagingSenderId: '29464535100',
    projectId: 'iot-feeder-f8e4f',
    databaseURL: 'https://iot-feeder-f8e4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-feeder-f8e4f.appspot.com',
    iosClientId: '29464535100-4uka1bruqffkdihp9uqsmruur3q3nf1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFeeder',
  );
}
